# Лабораторная работа 3

## Описание модели

Данные содержат 830 записей и 6 атрибутов. Датасет содержит информацию для скрининга рака молочной железы.

### Attributes 

- BI-RADS assessment: 1 to 5 
- Age: patient's age in years 
- Shape: mass shape: round=1 oval=2 lobular=3 irregular=4 
- Margin: mass margin: circumscribed=1 microlobulated=2 obscured=3 ill-defined=4 spiculated=5 
- Density: mass density high=1 iso=2 low=3 fat-containing=4 
- Severity: benign=0 or malignant=1 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("cleaned_data.csv")

In [3]:
data.head()

BI-RADS  Age  Shape  Margin  Density  Severity
0        5   67      3       5        3         1
1        5   58      4       5        3         1
2        4   28      1       1        3         0
3        5   57      1       5        3         1
4        5   76      1       4        3         1

In [4]:
min_ = data.min()
max_ = data.max()
mean_ = data.mean()
std_ = data.std()
nulls = data.isnull().sum()
stats = pd.DataFrame({'Пропуски': nulls, 'Мин.': min_, 'Макс.': max_, 'Средн.': mean_, 'Ст. откл.': std_})
stats

Пропуски  Мин.  Макс.     Средн.  Ст. откл.
BI-RADS          0     0     55   4.393976   1.888371
Age              0    18     96  55.781928  14.671782
Shape            0     1      4   2.781928   1.242361
Margin           0     1      5   2.813253   1.567175
Density          0     1      4   2.915663   0.350936
Severity         0     0      1   0.485542   0.500092

In [5]:
#Разбиение данных на тренировочные и тестовые
from sklearn.model_selection import train_test_split

x, y = data.iloc[:, 0:5].values, data.iloc[:, 5].values
X_train, X_test, y_train, y_test = \
        train_test_split(x, y, test_size=0.3, random_state=0)

In [6]:
from sklearn.preprocessing import StandardScaler
stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

In [7]:
from sklearn.linear_model import Perceptron
ppn = Perceptron(eta0=0.1, random_state=0,max_iter=40)
ppn.fit(X_train_std, y_train) 
y_pred = ppn.predict(X_test_std) 
print('Чиcлo ошибочно классифицированных образцов : %d ' % (y_test != y_pred).sum())

from sklearn.metrics import confusion_matrix
confmat = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(confmat)

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score
print('Точность доброкачественная: %.3f' % precision_score(y_true=y_test, y_pred=y_pred, pos_label=0)) 
print('Точность злокачественная: %.3f' % precision_score(y_true=y_test, y_pred=y_pred, pos_label=1))
print('Полнота доброкачественная: %.3f' % recall_score(y_true=y_test, y_pred=y_pred, pos_label=0)) 
print('Полнота злокачественная: %.3f' % recall_score(y_true=y_test, y_pred=y_pred, pos_label=1)) 
print('Верность: %.3f' % accuracy_score(y_true=y_test, y_pred=y_pred))

Чиcлo ошибочно классифицированных образцов : 63 
[[108  23]
 [ 40  78]]
Точность доброкачественная: 0.730
Точность злокачественная: 0.772
Полнота доброкачественная: 0.824
Полнота злокачественная: 0.661
Верность: 0.747


In [8]:
from sklearn.tree import DecisionTreeClassifier
import mlxtend
from mlxtend.plotting import plot_decision_regions
tree = DecisionTreeClassifier (criterion='entropy', max_depth=3, random_state=0)
tree.fit(X_train_std, y_train)
y_pred = tree.predict(X_test_std)
print('Чиcлo ошибочно классифицированных образцов : %d ' % (y_test != y_pred).sum())
from sklearn.metrics import confusion_matrix
confmat = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(confmat)
print('Точность доброкачественная: %.3f' % precision_score(y_true=y_test, y_pred=y_pred, pos_label=0)) 
print('Точность злокачественная: %.3f' % precision_score(y_true=y_test, y_pred=y_pred, pos_label=1))
print('Полнота доброкачественная: %.3f' % recall_score(y_true=y_test, y_pred=y_pred, pos_label=0)) 
print('Полнота злокачественная: %.3f' % recall_score(y_true=y_test, y_pred=y_pred, pos_label=1)) 
print('Верность: %.3f' % accuracy_score(y_true=y_test, y_pred=y_pred))

Чиcлo ошибочно классифицированных образцов : 42 
[[108  23]
 [ 19  99]]
Точность доброкачественная: 0.850
Точность злокачественная: 0.811
Полнота доброкачественная: 0.824
Полнота злокачественная: 0.839
Верность: 0.831


In [24]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=6, p=2, metric='minkowski')
knn.fit(X_train_std, y_train)
y_pred = knn.predict(X_test_std)
print('Чиcлo ошибочно классифицированных образцов : %d ' % (y_test != y_pred).sum())
from sklearn.metrics import confusion_matrix
confmat = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(confmat)
print('Точность доброкачественная: %.3f' % precision_score(y_true=y_test, y_pred=y_pred, pos_label=0)) 
print('Точность злокачественная: %.3f' % precision_score(y_true=y_test, y_pred=y_pred, pos_label=1))
print('Полнота доброкачественная: %.3f' % recall_score(y_true=y_test, y_pred=y_pred, pos_label=0)) 
print('Полнота злокачественная: %.3f' % recall_score(y_true=y_test, y_pred=y_pred, pos_label=1))  
print('Верность: %.3f' % accuracy_score(y_true=y_test, y_pred=y_pred))

Чиcлo ошибочно классифицированных образцов : 52 
[[105  26]
 [ 26  92]]
Точность доброкачественная: 0.802
Точность злокачественная: 0.780
Полнота доброкачественная: 0.802
Полнота злокачественная: 0.780
Верность: 0.791


In [10]:
from sklearn.svm import SVC
svm =SVC(kernel='rbf', random_state=0, gamma=40, C=1.0)
svm.fit(X_train_std, y_train)
y_pred = svm.predict(X_test_std)
print('Чиcлo ошибочно классифицированных образцов : %d ' % (y_test != y_pred).sum())
from sklearn.metrics import confusion_matrix
confmat = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(confmat)
print('Точность доброкачественная: %.3f' % precision_score(y_true=y_test, y_pred=y_pred, pos_label=0)) 
print('Точность злокачественная: %.3f' % precision_score(y_true=y_test, y_pred=y_pred, pos_label=1))
print('Полнота доброкачественная: %.3f' % recall_score(y_true=y_test, y_pred=y_pred, pos_label=0)) 
print('Полнота злокачественная: %.3f' % recall_score(y_true=y_test, y_pred=y_pred, pos_label=1)) 
print('Верность: %.3f' % accuracy_score(y_true=y_test, y_pred=y_pred))


Чиcлo ошибочно классифицированных образцов : 61 
[[ 84  47]
 [ 14 104]]
Точность доброкачественная: 0.857
Точность злокачественная: 0.689
Полнота доброкачественная: 0.641
Полнота злокачественная: 0.881
Верность: 0.755
